### ISSUE TITLE
データ構造

### ISSUE THREAD

**Issue by ryoksmt** [ryoksmt/common#1]
- Project Type [REST]
- Operation Type [MySQL, REST, Driver]
  - MySQL
    - DataBase
      - name
      - id
      - Table
        - name
        - id
          - Field
            - name
            - id
            - type

**Comment by ryoksmt** [comment]
コマンド
- common-ctl
  - サブコマンド
    - create
    - delete
    - update
  - リソース

**Comment by ryoksmt** [comment]
```
ProjectName: SampleProject
ProjectID: 541A9E90-D9AE-4FD4-8D05-828445DC6C1A
ProjectStructure: CleanArchitecture
ProjectType: REST
Operations:
- Data:
  DataType:
  - MySQL:
    DataBases:
    - SampleDB01:
      - Tables:
        - SampleTable01:
          - Fields:
            - name: sample_field
              uuid: 8109BC56-583C-43D6-AF56-CDC9C465E513
              type: string
```
